import { useEffect,useState } from 'react';import { supabase } from '../../lib/supabaseClient';
export default function Admin(){const [brands,setBrands]=useState([]);useEffect(()=>{refresh()},[]);async function refresh(){const {data}=await supabase.from('brands').select('*').order('slug');setBrands(data||[])}
async function onCreateBrand(e){e.preventDefault();const f=new FormData(e.currentTarget);const payload={slug:f.get('slug'),name:f.get('name'),description:f.get('description'),instagram:f.get('instagram'),mp_fee:Number(f.get('mp_fee')||10),logo_url:f.get('logo_url')||null,ship_domicilio:f.get('ship_domicilio')?Number(f.get('ship_domicilio')):null,ship_sucursal:f.get('ship_sucursal')?Number(f.get('ship_sucursal')):null,ship_free_from:Number(f.get('ship_free_from')||0),transfer_alias:f.get('transfer_alias')||null,transfer_titular:f.get('transfer_titular')||null};
const {error}=await supabase.from('brands').insert(payload);if(error)return alert(error.message);alert('Marca creada');e.currentTarget.reset();refresh();}
async function onAssignVendor(e){e.preventDefault();const f=new FormData(e.currentTarget);const email=f.get('email');const brand_slug=f.get('brand_slug');const {data:prof}=await supabase.from('profiles').select('id').eq('email',email).single();if(!prof)return alert('Ese email no tiene perfil. Que se loguee una vez.');const {error}=await supabase.from('vendor_brands').insert({user_id:prof.id,brand_slug});if(error)return alert(error.message);alert('Vendor asignado');}
async function onSaveSecrets(e){e.preventDefault();const f=new FormData(e.currentTarget);const slug=f.get('slug');const patch={mp_access_token:f.get('mp_access_token')||null,mp_public_key:f.get('mp_public_key')||null,transfer_alias:f.get('transfer_alias')||null,transfer_titular:f.get('transfer_titular')||null};const {error}=await supabase.from('brands').update(patch).eq('slug',slug);if(error)return alert(error.message);alert('Actualizado');refresh();}
return(<main className='container'><h1 className='h1'>Admin</h1><div className='card'><strong>Crear marca</strong><form onSubmit={onCreateBrand} className='grid' style={{gridTemplateColumns:'repeat(2,1fr)'}}><div><label>Slug</label><input className='input' name='slug' required/></div><div><label>Nombre</label><input className='input' name='name' required/></div><div><label>Descripción</label><input className='input' name='description'/></div><div><label>Instagram (URL)</label><input className='input' name='instagram' placeholder='https://instagram.com/...'/></div><div><label>% MP</label><input className='input' name='mp_fee' type='number' min='0' defaultValue='10'/></div><div><label>Logo (URL)</label><input className='input' name='logo_url' placeholder='https://...'/></div><div><label>Envío domicilio (ARS)</label><input className='input' name='ship_domicilio' type='number' min='0' placeholder='(vacío = desactivar)'/></div><div><label>Envío sucursal (ARS)</label><input className='input' name='ship_sucursal' type='number' min='0' placeholder='(vacío = desactivar)'/></div><div><label>Envío gratis desde (ARS)</label><input className='input' name='ship_free_from' type='number' min='0' defaultValue='0'/></div><div style={{gridColumn:'1/-1'}}><button className='btn'>Crear</button></div></form></div>
<h2 className='h2'>Marcas</h2><div className='grid' style={{gridTemplateColumns:'repeat(auto-fill, minmax(320px, 1fr))'}}>{brands.map(b=>(<div className='card' key={b.slug}><div className='row'><div style={{display:'flex',alignItems:'center',gap:10}}><img src={b.logo_url||'/logo.png'} alt={b.name} style={{width:34,height:34,objectFit:'contain',borderRadius:8,background:'#111',border:'1px solid #151515'}}/><strong>{b.name}</strong></div><a className='badge' href={`/marcas/${b.slug}`}>Ver</a></div><div className='small'>IG: <a href={b.instagram} target='_blank' rel='noreferrer'>{b.instagram}</a></div><div className='small'>MP %: {b.mp_fee??'global'}</div><div className='small'>Envíos: {b.ship_domicilio?`Dom $${b.ship_domicilio}`:'Dom off'} · {b.ship_sucursal?`Suc $${b.ship_sucursal}`:'Suc off'} · Free desde ${b.ship_free_from||0}</div>
<form onSubmit={onAssignVendor} className='mt'><strong>Asignar vendor</strong><div className='grid' style={{gridTemplateColumns:'2fr 1fr'}}><div><label>Email del vendor</label><input className='input' name='email' type='email' required/></div><input type='hidden' name='brand_slug' value={b.slug}/><div><button className='btn'>Asignar</button></div></div></form>
<form onSubmit={onSaveSecrets} className='mt'><strong>Conf. sensible (solo admin)</strong><input type='hidden' name='slug' value={b.slug}/><div><label>MP Access Token</label><input className='input' name='mp_access_token' defaultValue={b.mp_access_token||''} placeholder='token secreto'/></div><div><label>MP Public Key (opcional)</label><input className='input' name='mp_public_key' defaultValue={b.mp_public_key||''}/></div><div><label>Transferencia alias/CBU</label><input className='input' name='transfer_alias' defaultValue={b.transfer_alias||''}/></div><div><label>Titular</label><input className='input' name='transfer_titular' defaultValue={b.transfer_titular||''}/></div><div className='mt'><button className='btn'>Guardar</button></div></form></div>))}</div></main>)}
